function com_typeracer_guest_Guest(){var r='',vb='\n',wb='" for "gwt:onLoadErrorFn"',xb='" for "gwt:onPropertyErrorFn"',yb='"><\/script>',zb='#',Ab='.cache.html',Bb='/',Cb='//',Z='//imasdk.googleapis.com/js/sdkloader/ima3.js',$='3446A23C8596F309CBC2040F5D2D826F',_='4FA3782D4B6C3806B2549DCB79F19FC6',ab='6045398DEA6D2A50DA9ED561A4A69168',bb='63F74331B53790E1733D87EFE927EAE2',cb='9B62BF065CF244E806043D39D0EB7336',Db=':',u=':1',Eb='::',Fb='<script defer="defer">com_typeracer_guest_Guest.onInjectionDone(\'com.typeracer.guest.Guest\')<\/script>',Gb='<script id="',Hb='<script language="javascript" src="//imasdk.googleapis.com/js/sdkloader/ima3.js"><\/script>',Ib='<script language="javascript" src="https://www.gstatic.com/charts/loader.js"><\/script>',Jb='=',Kb='?',db='B67227995EF9014B22901C1B49C4C9D8',eb='Bad handler "',fb='DF22BEF1B79660CA6516EA0723527501',gb='DOMContentLoaded',hb='EDA3F724B990CE223D138F650FD3A961',Lb='SCRIPT',Mb='Unexpected exception in debug mode detection, debug mode will be disabled: ',Nb='__gwt_marker_com.typeracer.guest.Guest',Ob='base',Pb='baseUrl',ib='begin',G='bootstrap',H='chromeWithColNumbers',Qb='clear.cache.gif',s='com.typeracer.guest.Guest',Rb='com.typeracer.guest.Guest.nocache.js',Sb='com.typeracer.guest.Guest::',I='content',B='debug',J='end',p='false',Tb='gecko',K='gecko1_8',Ub='gwt.codesvr=',Vb='gwt.hosted=',Wb='gwt.hybrid',Xb='gwt:onLoadErrorFn',Yb='gwt:onPropertyErrorFn',Zb='gwt:property',$b='hosted.html?com_typeracer_guest_Guest',jb='https://www.gstatic.com/charts/loader.js',L='ie10',M='ie6',N='ie8',O='ie9',_b='iframe',ac='img',bc="javascript:''",kb='loadExternalRefs',cc='meta',dc='moduleRequested',lb='moduleStartup',P='msie',ec='name',t='off',v='on',C='opera',fc='position:absolute;width:0;height:0;border:none',z='safari',gc='script',hc='selectingPermutation',w='startup',mb='true',ic='undefined',jc='unknown',Q='user.agent',kc='webkit';var o=window,m=document,q=o.__gwtStatsEvent?function(a){return o.__gwtStatsEvent(a)}:null,x=o.__gwtStatsSessionId?o.__gwtStatsSessionId:null,nb,ob,pb,R=r,qb={},A=[],D=[],rb=[],sb=0,tb,S;q&&q({moduleName:s,sessionId:x,subSystem:w,evtGroup:G,millis:(new Date).getTime(),type:ib});if(!o.__gwt_stylesLoaded){o.__gwt_stylesLoaded={}}if(!o.__gwt_scriptsLoaded){o.__gwt_scriptsLoaded={}}function E(){var c=false;try{var b=o.location.search;return (b.indexOf(Ub)!=-1||(b.indexOf(Vb)!=-1||o.external&&o.external.gwtOnLoad))&&b.indexOf(Wb)==-1}catch(a){}E=function(){return c};return c}
function T(){if(nb&&ob){var c=m.getElementById(s);var b=c.contentWindow;if(E()){b.__gwt_getProperty=function(a){return F(a)}}com_typeracer_guest_Guest=null;b.gwtOnLoad(tb,s,R,sb);q&&q({moduleName:s,sessionId:x,subSystem:w,evtGroup:lb,millis:(new Date).getTime(),type:J})}}
function mc(){function f(a){var b=a.lastIndexOf(zb);if(b==-1){b=a.length}var c=a.indexOf(Kb);if(c==-1){c=a.length}var d=a.lastIndexOf(Bb,Math.min(c,b));return d>=0?a.substring(0,d+1):r}
function g(a){if(a.match(/^\w+:\/\//)){}else{var b=m.createElement(ac);b.src=a+Qb;a=f(b.src)}return a}
function h(){var a=lc(Pb);if(a!=null){return a}return r}
function i(){var b=m.getElementsByTagName(gc);for(var a=0;a<b.length;++a){if(b[a].src.indexOf(Rb)!=-1){return f(b[a].src)}}return r}
function j(){var a;if(typeof isBodyLoaded==ic||!isBodyLoaded()){var c=Nb;var b;m.write(Gb+c+yb);b=m.getElementById(c);a=b&&b.previousSibling;while(a&&a.tagName!=Lb){a=a.previousSibling}if(b){b.parentNode.removeChild(b)}if(a&&a.src){return f(a.src)}}return r}
function k(){var a=m.getElementsByTagName(Ob);if(a.length>0){return a[a.length-1].href}return r}
function l(){var a=m.location;return a.href==a.protocol+Cb+a.host+a.pathname+a.search+a.hash}
var e=h();if(e==r){e=i()}if(e==r){e=j()}if(e==r){e=k()}if(e==r&&l()){e=f(m.location.href)}e=g(e);R=e;return e}
function nc(){var h=document.getElementsByTagName(cc);for(var e=0,i=h.length;e<i;++e){var d=h[e],c=d.getAttribute(ec),b;if(c){c=c.replace(Sb,r);if(c.indexOf(Eb)>=0){continue}if(c==Zb){b=d.getAttribute(I);if(b){var f,g=b.indexOf(Jb);if(g>=0){c=b.substring(0,g);f=b.substring(g+1)}else{c=b;f=r}qb[c]=f}}else if(c==Yb){b=d.getAttribute(I);if(b){try{S=eval(b)}catch(a){alert(eb+b+xb)}}}else if(c==Xb){b=d.getAttribute(I);if(b){try{tb=eval(b)}catch(a){alert(eb+b+wb)}}}}}}
function oc(a,b){return b in A[a]}
function lc(b){var a=qb[b];return a==null?null:a}
function n(a,e){var b=rb;for(var c=0,d=a.length-1;c<d;++c){b=b[a[c]]||(b[a[c]]=[])}b[a[d]]=e}
function F(a){var b=D[a](),c=A[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(S){S(a,d,b)}throw null}
var U;function ub(){if(!U){U=true;var a=m.createElement(_b);a.src=bc;a.id=s;a.style.cssText=fc;a.tabIndex=-1;m.body.appendChild(a);q&&q({moduleName:s,sessionId:x,subSystem:w,evtGroup:lb,millis:(new Date).getTime(),type:dc});a.contentWindow.location.replace(R+V)}}
D[H]=function(){if(Error&&Error.captureStackTrace){try{null.a()}catch(a){if(a.stack){var b=a.stack.split(vb);if(b&&(b.length>1&&/:\d+:\d+\)?\s*$/.test(b[1]))){return true}}}}return false};A[H]={'false':0,'true':1};D[B]=function(){try{var b=null;var c=/[?&]debug=(.*?)(?:&|$)/.exec(location.search);if(c)b=c[1];if(b==null||!oc(B,b)){return t}return b}catch(a){alert(Mb+a);return t}};A[B]={off:0,on:1};D[Q]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(C)!=-1}())return C;if(function(){return b.indexOf(kc)!=-1}())return z;if(function(){return b.indexOf(P)!=-1&&m.documentMode>=10}())return L;if(function(){return b.indexOf(P)!=-1&&m.documentMode>=9}())return O;if(function(){return b.indexOf(P)!=-1&&m.documentMode>=8}())return N;if(function(){var a=/msie ([0-9]+)\.([0-9]+)/.exec(b);if(a&&a.length==3)return c(a)>=6000}())return M;if(function(){return b.indexOf(Tb)!=-1}())return K;return jc};A[Q]={gecko1_8:0,ie10:1,ie6:2,ie8:3,ie9:4,opera:5,safari:6};com_typeracer_guest_Guest.onScriptLoad=function(){if(U){ob=true;T()}};com_typeracer_guest_Guest.onInjectionDone=function(){nb=true;q&&q({moduleName:s,sessionId:x,subSystem:w,evtGroup:kb,millis:(new Date).getTime(),type:J});T()};nc();mc();var y;var V;if(E()){if(o.external&&(o.external.initModule&&o.external.initModule(s))){o.location.reload();return}V=$b;y=r}q&&q({moduleName:s,sessionId:x,subSystem:w,evtGroup:G,millis:(new Date).getTime(),type:hc});if(!E()){try{n([p,t,z],$);n([p,v,z],$+u);n([p,t,M],_);n([p,v,M],_+u);n([p,t,L],ab);n([p,v,L],ab+u);n([mb,t,z],bb);n([mb,v,z],bb+u);n([p,t,O],cb);n([p,v,O],cb+u);n([p,t,K],db);n([p,v,K],db+u);n([p,t,C],fb);n([p,v,C],fb+u);n([p,t,N],hb);n([p,v,N],hb+u);y=rb[F(H)][F(B)][F(Q)];var W=y.indexOf(Db);if(W!=-1){sb=Number(y.substring(W+1));y=y.substring(0,W)}V=y+Ab}catch(a){return}}var X;function Y(){if(!pb){pb=true;T();if(m.removeEventListener){m.removeEventListener(gb,Y,false)}if(X){clearInterval(X)}}}
if(m.addEventListener){m.addEventListener(gb,function(){ub();Y()},false)}var X=setInterval(function(){if(/loaded|complete/.test(m.readyState)){ub();Y()}},50);q&&q({moduleName:s,sessionId:x,subSystem:w,evtGroup:G,millis:(new Date).getTime(),type:J});q&&q({moduleName:s,sessionId:x,subSystem:w,evtGroup:kb,millis:(new Date).getTime(),type:ib});if(!__gwt_scriptsLoaded[jb]){__gwt_scriptsLoaded[jb]=true;document.write(Ib)}if(!__gwt_scriptsLoaded[Z]){__gwt_scriptsLoaded[Z]=true;document.write(Hb)}m.write(Fb)}
com_typeracer_guest_Guest();